library(dplyr)
library(readr)
library(kaggler)
library(shiny)
library(recipes)
library(shinythemes)
library(shinyWidgets)
library(shinydashboard)
library(ggplot2)
library(DT)
library(shinyWidgets) 
library(plsdepot)
library(visreg)
library(caret)
library(plotly)
library(rsconnect)


happy_data <- read_csv("world-happiness-report-2021.csv")
happy=select(happy_data, "Country name", "Ladder score", "Logged GDP per capita", "Social support", "Healthy life expectancy", "Freedom to make life choices", "Generosity", "Perceptions of corruption" )
happy2 <- select(happy_data, "Country name", "Regional indicator", "Ladder score", "Logged GDP per capita", "Social support", "Healthy life expectancy", "Freedom to make life choices", "Generosity", "Perceptions of corruption" )
regions= unique(happy2$"Regional indicator")

happy_w = rename(happy, CountryName = "Country name", LadderScore = "Ladder score", LoggedGDPperCapita = "Logged GDP per capita", SocialSupport = "Social support", HealthLifeExpectancy = "Healthy life expectancy", FreedomToMakeLifeChoices = "Freedom to make life choices", PerceptionsOfCorruption="Perceptions of corruption")